cd /Users/anuragvats/Dev/littest

lit init
echo "-----------------------------------------------------------------1----"

echo "First line first file" > file1

lit status
echo "-----------------------------------------------------------------2----"
lit commit 'Adding file1'
echo "-----------------------------------------------------------------3----"

echo "Second line first file" >> file1

lit status
echo "-----------------------------------------------------------------4----"
lit commit 'Extending file1'
echo "-----------------------------------------------------------------5----"
mkdir sub
echo "First line second file" > sub/file2

lit commit 'Adding file2'

echo "-----------------------------------------------------------------6----"

lit log
echo "-----------------------------------------------------------------7----"
echo "Second line second file" >> sub/file2
echo "Third line first file" >> file1
lit status
lit commit 'Extending files'
echo "-----------------------------------------------------------------8----"
lit checkout r2
echo "First line third file" > file3

#lit status
#lit commit 'Branch from r2 - Adding file3'
#echo "-----------------------------------------------------------------9----"
#lit checkout r1
#echo "First line fourth file" > file4
#
#lit status
#lit commit 'Branch from r1 - Adding file4'
#echo "-----------------------------------------------------------------10---"
#lit log
#echo "-----------------------------------------------------------------11---"
## #echo "-----------------------------------------------------------------12---"